### ISSUE TITLE
Question: why is this URL not returning anything?

### ISSUE THREAD

**Issue by jakewilliami** [scrapehero-code/amazon-scraper#1]
Firstly, I just wanted to say, great work and great article!

So I am making a web scraper based on yours, that is going to search amazon for a list of DVDs or Blu-rays based on title alone (hopefully with little error), and return the price.  I have the test URL `https://www.amazon.com/Sean-Connery/dp/B011MHCHTQ/`, but it is returning null in every field.  Do you know why this is?

Thanks!

**Comment by scrapehero-code** [comment]
You might most probably be getting blocked. Can you try [changing User Agents](https://www.scrapehero.com/how-to-fake-and-rotate-user-agents-using-python-3/).
